# Generated by Django 4.1.3 on 2022-11-05 17:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiarrheaSymptom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="submitted by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diarrhea Symptom",
                "db_table": "diarrhea_symptom",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Water",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_collection",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Enter a date",
                        verbose_name="Date of collection",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("T", "Tap"), ("P", "Pond"), ("R", "River")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="submitted by",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="address.site",
                        verbose_name="Sample Collection Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Water Sample",
                "ordering": ["-date_of_collection"],
            },
        ),
        migrations.CreateModel(
            name="Vegetable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_collection",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Enter a date",
                        verbose_name="Date of collection",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Vegetable Name"),
                ),
                (
                    "origin",
                    models.CharField(
                        max_length=200, verbose_name="Origin of the vegetable"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="submitted by",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="address.site",
                        verbose_name="Sample Collection Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vegetable Sample",
            },
        ),
        migrations.CreateModel(
            name="Stool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_collection",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Enter a date",
                        verbose_name="Date of collection",
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(150),
                        ],
                        verbose_name="Patient's Age",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Others")],
                        max_length=1,
                        verbose_name="Patient's Gender",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="submitted by",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="address.site",
                        verbose_name="Sample Collection Site",
                    ),
                ),
                ("symptoms", models.ManyToManyField(to="sample.diarrheasymptom")),
            ],
            options={
                "verbose_name": "Stool Sample",
            },
        ),
    ]
