# Generated by Django 4.1.3 on 2022-11-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slideimage",
            name="image",
            field=models.ImageField(
                default=None, upload_to="sample_images", verbose_name="Slide Image"
            ),
        ),
    ]
