# Generated by Django 4.1.3 on 2022-11-28 09:30

from django.db import migrations, models
import sample.models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0003_alter_slideimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slideimage",
            name="image",
            field=models.ImageField(
                upload_to=sample.models.upload_samples, verbose_name="Slide Image"
            ),
        ),
    ]
