# Generated by Django 4.1.3 on 2022-11-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0004_alter_slideimage_image"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="slideimage",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("image_type__exact", "S"),
                    ("image_type__exact", "B"),
                    _connector="OR",
                ),
                name="image_type_S_or_B",
            ),
        ),
    ]
