# Generated by Django 4.1.3 on 2022-11-28 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0005_slideimage_image_type_s_or_b"),
    ]

    operations = [
        migrations.AddField(
            model_name="vegetable",
            name="ward",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(32),
                ],
            ),
        ),
        migrations.AddField(
            model_name="water",
            name="ward",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(32),
                ],
            ),
        ),
    ]
