# Generated by Django 4.1.3 on 2022-12-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0006_vegetable_ward_water_ward"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vegetable",
            name="origin",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="water",
            name="use",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
