# Generated by Django 4.1.3 on 2022-12-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0007_alter_vegetable_origin_alter_water_use"),
    ]

    operations = [
        migrations.AddField(
            model_name="stool",
            name="lat",
            field=models.DecimalField(
                decimal_places=6,
                default=27.708325,
                max_digits=9,
                verbose_name="Latitude",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stool",
            name="long",
            field=models.DecimalField(
                decimal_places=6,
                default=85.320585,
                max_digits=9,
                verbose_name="Longitude",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vegetable",
            name="lat",
            field=models.DecimalField(
                decimal_places=6,
                default=27.708325,
                max_digits=9,
                verbose_name="Latitude",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vegetable",
            name="long",
            field=models.DecimalField(
                decimal_places=6,
                default=85.320585,
                max_digits=9,
                verbose_name="Longitude",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="water",
            name="lat",
            field=models.DecimalField(
                decimal_places=6,
                default=27.708325,
                max_digits=9,
                verbose_name="Latitude",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="water",
            name="long",
            field=models.DecimalField(
                decimal_places=6,
                default=85.320585,
                max_digits=9,
                verbose_name="Longitude",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="name",
            field=models.CharField(
                choices=[
                    ("CU", "Cucumber"),
                    ("CA", "Cabbage"),
                    ("TO", "Tomato"),
                    ("RA", "Radish"),
                    ("CR", "Carrot"),
                    ("SP", "Spinach"),
                    ("CH", "Chilli"),
                ],
                max_length=2,
            ),
        ),
    ]
