# Generated by Django 4.1.3 on 2022-12-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0009_remove_stool_lat_remove_stool_long"),
    ]

    operations = [
        migrations.AddField(
            model_name="standard",
            name="sample_type",
            field=models.CharField(
                choices=[("W", "Water"), ("V", "Vegetable")], default="W", max_length=1
            ),
            preserve_default=False,
        ),
    ]
