# Generated by Django 4.1.3 on 2022-12-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0011_alter_standard_dilution_factor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standard",
            name="dilution_factor",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="standard",
            name="expected_concentration",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="standard",
            name="observed_concentration",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
