# Generated by Django 4.1.3 on 2022-12-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0012_alter_standard_dilution_factor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standard",
            name="dilution_factor",
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="standard",
            name="sample_type",
            field=models.CharField(
                choices=[("W", "Water"), ("V", "Vegetable"), ("S", "Stool")],
                max_length=1,
            ),
        ),
    ]
