# Generated by Django 4.1.3 on 2023-03-27 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0001_initial"),
        ("sample", "0014_slideimage_approved_slideimage_approved_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="slideimage",
            name="annotated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="slideimage",
            name="annotator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="annotator",
                to="annotation.annotator",
            ),
        ),
    ]
