# Generated by Django 4.1.3 on 2023-11-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0017_alter_water_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="slideimage",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="slideimage",
            name="reviewed",
            field=models.BooleanField(default=False),
        ),
    ]
