# Generated by Django 4.1.3 on 2023-03-27 05:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0003_annotation_annotated_on"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="annotation",
            unique_together=set(),
        ),
    ]
