# Generated by Django 4.1.3 on 2023-05-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0004_alter_annotation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="has_cyst",
            field=models.BooleanField(default=False),
        ),
    ]
