# Generated by Django 4.1.3 on 2024-04-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0005_annotation_has_cyst"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.UniqueConstraint(
                fields=("image", "annotator"), name="unique_image_annotator_pair"
            ),
        ),
    ]
