# Generated by Django 4.1.3 on 2022-11-21 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provinces",
                to="address.province",
            ),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="districts",
                to="address.district",
            ),
        ),
        migrations.AlterField(
            model_name="ward",
            name="municipality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="municipalities",
                to="address.municipality",
            ),
        ),
    ]
