# Generated by Django 4.1.3 on 2022-11-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "address",
            "0002_alter_district_province_alter_municipality_district_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="province",
            name="code",
            field=models.CharField(default=None, max_length=2, unique=True),
        ),
    ]
