# Generated by Django 4.1.3 on 2023-10-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_province_code"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="provinces",
            field=models.ManyToManyField(blank=True, to="address.province"),
        ),
    ]
